MARP-528 chat gpt assistant it should be possible to copy result
axonivy-market/openai-connector pull request #55
Opened 2024-07-09 04:35 UTC by linhpd-axonivy

2024-07-10 06:40 UTC, ntqdinh-axonivy requested changes

2024-07-10 06:40 UTC, ntqdinh-axonivy commented on openai-assistant/src/com/axonivy/connector/openai/assistant/ui/CopyableInfoDialog.java
> +    return String.format("#%02x%02x%02x", rgb.red, rgb.green, rgb.blue);
Could we create a constant for these format since its name can somehow explain the pattern & easy to maintain/refactor for later?

2024-07-10 08:15 UTC, ntqdinh-axonivy approved these changes
Tested & LGTM

2024-07-10 08:19 UTC, merged

2024-07-24 07:28 UTC, ivy-rew commented
> Tested & LGTM

How did you test it @ntqdinh-axonivy ? Apparently the feature is not working at runtime :thinking:

2024-07-24 07:29 UTC, ivy-rew commented
True I was on vacation; but I don't understand why you didn't keep me in the loop of such changes? @linhpd-axonivy

2024-07-24 07:31 UTC, ivy-rew commented on openai-assistant/libs/commonmark-0.22.0.jar
Adding binaries to SCM is bad practice and makes the GIT workspace slow. WE can no longer undo this performance bottleneck. :snail:

2024-07-24 07:37 UTC, linhpd-axonivy commented on openai-assistant/libs/commonmark-0.22.0.jar
It was my mistake. I apologize and will make sure it doesn't happen again.

2024-07-24 10:10 UTC, ntqdinh-axonivy commented
> > Tested & LGTM
> 
> How did you test it @ntqdinh-axonivy ? Apparently the feature is not working at runtime 🤔 . If you test such a feature you should only do it with the jar-s generated by a build pipeline. And not out of a ide-test-environment or something. Otherwise we will again face such issues, where the actually compiled code is different than the dev-artifacts.

 Oops, my bad. I used Eclipse RCP to run the app on Designer 11 &  included external libs without being aware that it was an inappropriate approach to test this feature. Thanks for your feedback. I will be much more careful in the next time.